# Generated by Django 6.0.4 on 2026-04-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='my_Product',
        ),
    ]
