# Generated by Django 6.0.4 on 2026-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('village_name', models.CharField(max_length=100)),
            ],
        ),
    ]
